### ISSUE TITLE
今年の目標とチャレンジすることを決める

### ISSUE THREAD

**Issue by ETmassa** [shin3505/ADNiStest#15]
いつもモデルの目標で悩むので、早めに決めとく
あと、モデルのアピールポイントとなるチャレンジ項目を作る

**Comment by 1012065-z220** [comment]
疲れないように頑張る（効率的に頑張る）

**Comment by shin3505-1** [comment]
チャレンジ目標：開発環境のさらなる効率化？
↑の一環として、pull requestやpush時に自動コンパイルするようにgithub actionsを使って設定する？
dockerを使ってev3rtをコンパイルする環境はすでにあった。
https://qiita.com/Shitimi_613/items/35b3a30ba55ee6f8e01d

これがあると、今までcygwinとかgcc入れたりだとかの環境構築が不要になる。
なぜなら、上記のようなコンパイル環境を仮想マシン上に作れるのがdockerの強みだから。

**Comment by shin3505-1** [comment]
競技的には、機械学習？
シミュレーションの詳細が出ないとそこは決めれないか？

**Comment by 0096431-z220** [comment]
シミュレーションを繰り返し実施して学習っていう機械学習できんかな？ライントレースとかも含めて。

**Comment by 1012065-z220** [comment]
パラメーターの適合などは、シミュレーションの繰り返しで学習させられそうですね。シミュレーションの結果から必要な情報が出力出来れば、あとは評価関数を作ってやるだけで出来そうなイメージ。（最適化ツールのライブラリがどこかに落ちていれば一番楽）

**Comment by 1012065-z220** [comment]
ランダム要素がどの程度あるのかを運営に聞いてみるか？（ランダム要素がないと全部仮想ラインだけで走らせられるのでは？）

**Comment by shin3505-1** [comment]
目標：リザルトタイムを〇〇s獲得する
（シミュレータならではの装飾語を↑に入れたい）
○○s：ベーシックの妥当な時間とゲームのエリアフル攻略or 妥当なラインを書く

**Comment by shin3505-1** [comment]
チャレンジ候補：・実機とシミュレーションの協調
　　　　　　　　・ロジックの妥当性検証（自動全網羅チェック）→★
　　　　　　　　　→バグの早期発見やアジャイル開発
　　　　　　　　・パッチあてなし（内々の目標、モデルには書けない）
　　　　　　　　・
