### ISSUE TITLE
競技規約の読み合わせ

### ISSUE THREAD

**Issue by shin3505-1** [shin3505/ADNiStest#5]
以下は要注意

・スタータの動き方
・ゲームのルール

↑シミュレータになるとここら辺がどうなるのかを要チェック

**Comment by ETmassa** [comment]
昨年の失敗は、読んでいなかったのではなく、読んでいたけど忘れてしまったのが原因？注意点や変更点はどこかにまとめてわかりやすくしておいた方がいい？

**Comment by MOSS0828** [comment]
自分たちの都合で読み違えてしまっていたので、こうなるかもしれないという注意が必要（ex.画角にブロックエリアが全部移るわけではない）

**Comment by shin3505-1** [comment]
FMEAじゃないけど、この情報がなくなると困るみたいなものは深堀してシチュエーションを考えることは大事かも

**Comment by 1012065-z220** [comment]
去年の件に関しては、「まさか画角にエリアが収まっていないなんてことはあるはずない」という先入観もだいぶあったと思います。だからもし収まっていなかったときにどうするかってことに気が付けなかった。
なので、↑でおっしゃられている通り、機能の前提条件や制約条件は深堀りして、競技規約で明記されていなければ対策案を考えるなどした方がよいかもしれません。

**Comment by shin3505-1** [comment]
読み合わせ完了
