### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by shin3505-1** [shin3505/ADNiStest#8]
・GitHub
・シミュレータ
・カメラシステム
etc.

**Comment by 1012065-z220** [comment]
シミュレータ、カメラシステム等の競技環境は競技環境構築イシューで管理

**Comment by shin3505-1** [comment]
githubは、IT推進室からの認可待ち（チェックシート相談中）だが先行して使っていいことは了承もらった。なので、githubのenterprise版でリポジトリを立てて自動コンパイルできるところまでをGW中に試したい。

**Comment by shin3505-1** [comment]
pythonは、sckit-learnのライブラリを使ってテストデータでの文字認識は何となくやった（udemyの講義にあったので）。だが、mnistの味見はできてない。いろいろ調べるとmnistを使うに当たっては、tensorFlowというプラッフォームを使うとよいらしい。これのインストールにあたってはpythonのVerにも依存するらしいので注意が必要。

**Comment by shin3505-1** [comment]
誰かやってほしいな～（GW中に）

**Comment by shin3505-1** [comment]
とりあえず手動でできたら、これのdockerにしてしまいたい。
そうすれば、だれのPCでもテストできるので。

**Comment by 0096431-z220** [comment]
dockerっての便利そうですねぇ。ちゃんと見てないけど！

**Comment by 1012065-z220** [comment]
小嶋さん情報ありがとうございます。mnist触るうえで参考にさせてもらいます。

**Comment by 1012065-z220** [comment]
・サーバ上でのAPPファイルの登録方法と管理方法については要検討
・Dockerについては、各個人のロボコンPCに作成推奨。
・Mnistは引き続き実施してみる
